[package]
name = "bbbot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
poise = "0.6.1"
quick-xml = "0.38.0"
shuttle-runtime = "0.56.0"
shuttle-serenity = "0.56.0"
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
